server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twilightdb?charset=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: twilight
    password: twilight

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 300
    shutdown-timeout: 100msx
    jedis:
      pool:
        max-active: 8
        min-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    cache-names: REDIS
  session:
    store-type: redis

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

tw:
  file-path-prefix: /Users/takaibun/IdeaProjects/data/


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
